"""Change in admin table

Revision ID: 1943e719d95e
Revises: 4b347671921b
Create Date: 2026-02-10 11:07:39.329685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1943e719d95e'
down_revision: Union[str, Sequence[str], None] = '4b347671921b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('username', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.create_unique_constraint(None, 'admins', ['username'])
    op.drop_column('admins', 'email')
    op.drop_column('admins', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('admins', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'admins', type_='unique')
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.drop_column('admins', 'username')
    # ### end Alembic commands ###
