"""Change in admin table

Revision ID: c5502d067d0a
Revises: 1943e719d95e
Create Date: 2026-02-10 11:35:09.095980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5502d067d0a'
down_revision: Union[str, Sequence[str], None] = '1943e719d95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('email', sa.String(), nullable=False))
    op.add_column('admins', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('admins', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('admins', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('admins_username_key'), 'admins', type_='unique')
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.drop_column('admins', 'hashed_password')
    op.drop_column('admins', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('admins', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.create_unique_constraint(op.f('admins_username_key'), 'admins', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('admins', 'is_active')
    op.drop_column('admins', 'is_superuser')
    op.drop_column('admins', 'password_hash')
    op.drop_column('admins', 'email')
    # ### end Alembic commands ###
